[project]
name = "ingestion-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiobotocore>=3.3.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi==0.116.1",
    "fastembed>=0.8.0",
    "greenlet>=3.3.2",
    "langchain-experimental>=0.4.1",
    "langchain-text-splitters>=1.1.1",
    "pydantic-settings>=2.13.1",
    "python-multipart==0.0.20",
    "qdrant-client>=1.17.1",
    "sqlalchemy>=2.0.48",
    "uvicorn>=0.42.0",
]
