"""add file_extension to document

Revision ID: 585aa228569c
Revises: 107bcd4d9235
Create Date: 2026-03-28 14:20:41.527765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585aa228569c'
down_revision: Union[str, Sequence[str], None] = '107bcd4d9235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestion_documents', sa.Column('file_extension', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestion_documents', 'file_extension')
    # ### end Alembic commands ###
