"""file_name unique=True

Revision ID: c2bcaa1b13b2
Revises: 0cac6c45baa0
Create Date: 2026-04-20 18:26:29.349775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bcaa1b13b2'
down_revision: Union[str, Sequence[str], None] = '0cac6c45baa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingestion_documents_file_name'), 'ingestion_documents', ['file_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_documents_file_name'), table_name='ingestion_documents')
    # ### end Alembic commands ###
